(define (problem swap_to_swap_2_2)
    (:domain blocksworld)
    (:requirements :strips)
    (:objects b1 b2 b3 b4)
    (:init (arm-empty) (clear b3) (clear b4) (on b3 b1) (on b4 b2) (on-table b1) (on-table b2))
    (:goal (and (arm-empty) (on-table b2) (on-table b1) (on b3 b2) (clear b3) (on b4 b1) (clear b4)))
)