(down robot1 tile1 tile3)
(paint-up robot1 tile1 tile3 color1)
(change-color robot1 color1 color2)
(change-color robot1 color2 color4)
(paint-right robot1 tile4 tile3 color4)
(change-color robot1 color4 color2)
(right robot1 tile3 tile4)
(paint-up robot1 tile2 tile4 color2)
(change-color robot1 color2 color3)
(paint-left robot1 tile3 tile4 color3)
(change-color robot1 color3 color5)
(change-color robot1 color5 color6)
(paint-down robot1 tile6 tile4 color6)
(change-color robot1 color6 color5)
(left robot1 tile4 tile3)
(paint-down robot1 tile5 tile3 color5)
; cost = 16 (unit cost)
