(define (problem blocksworld_fsp_example_problem)
    (:domain blocksworld)
    (:requirements :strips)
    (:objects b1 b10 b2 b3 b4 b5 b6 b7 b8 b9)
    (:init (arm-empty) (clear b1) (clear b2) (clear b4) (clear b7) (on b2 b3) (on b4 b5) (on b5 b6) (on b7 b8) (on b8 b9) (on b9 b10) (on-table b1) (on-table b10) (on-table b3) (on-table b6))
    (:goal (and (arm-empty) (clear b1) (on-table b1) (clear b2) (on-table b2) (clear b3) (on-table b3) (clear b4) (on-table b4) (clear b5) (on b5 b6) (on b6 b7) (on-table b7) (clear b8) (on b8 b9) (on b9 b10) (on-table b10)))
)