import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FAST_DOWNWARD_PATH = r"D:\fast-downward-24.06.1"
VAL_PATH = r"C:\Tools\Val-20211204.1-win64\bin\Validate.exe"
RESULT_ROOT = os.path.join(BASE_DIR, "results")
INSIGHTS_LIMIT = 10
OPERATIONS_LIMIT = 4
EXP_TRAINING_TRIALS = 3
EXP_TESTING_TRIALS = 3
BASIC_LLM_MODEL = "accounts/fireworks/models/llama4-scout-instruct-basic"
ADVANCED_LLM_MODEL = "accounts/fireworks/models/llama4-maverick-instruct-basic"
# LLM_DEFAULT_MODEL = BASIC_LLM_MODEL
# REFLECTION_LLM_MODEL = BASIC_LLM_MODEL
# INSIGHTS_LLM_MODEL = BASIC_LLM_MODEL
LLM_DEFAULT_MODEL = ADVANCED_LLM_MODEL
REFLECTION_LLM_MODEL = ADVANCED_LLM_MODEL
INSIGHTS_LLM_MODEL = ADVANCED_LLM_MODEL
EXP_FEWSHOTS = 2
LLM_QUERY_TRY_LIMIT_PER_KEY = 3
TRAINING_SUBSET = "train4"
TESTING_SUBSET = "test5"
EMBEDDINGS_TRAINING_SUBSET = "train5"
EMBEDDINGS_TESTING_SUBSET = "test5"